const fs=require('fs'),vm=require('vm'),path=require('path');
const base=path.resolve(__dirname,'..');const context={window:{}};vm.runInNewContext(fs.readFileSync(path.join(base,'story-content.js'),'utf8'),context);const chapters=context.window.VEREDA_CONTENT;
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
const pageLoader=fs.readFileSync(path.join(base,'page-loader-art.html'),'utf8');
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15M13 5l7 7-7 7"/></svg>';
const titles=['Toda luz<br>começa com<br><em>uma promessa.</em>','O que cabe<br>na promessa.','Antes da forma,<br><em>a escuta.</em>','Uma promessa<br>precisa de apoio.','O serviço<br><em>ganha desenho.</em>','A ideia está<br><em>nas suas mãos.</em>','A prévia vira<br><em>um acordo.</em>','Agora, a matéria<br>acompanha você.','A forma precisa<br>cumprir o combinado.','É luz a caminho<br><em>de alguém.</em>','O cuidado<br><em>também se mede.</em>','A IA sugere.<br>A pessoa decide.','Uma boa ideia<br>precisa passar<br>pela realidade.','O serviço<br><em>continua aceso.</em>','Toda entrega<br>ensina a próxima.','Promessa cumprida<br><em>acende a luz.</em>'];
const labels=['Da ideia à luz','Escopo','Requisitos · SLR','Fornecedores · UC','O processo SLM','Desenho','O acordo · SLA','Produção','Conferência','Entrega','Indicadores','Inteligência artificial','Proteção','Continuidade','Revisão · SIP','Luz'];
const tones=['light','light','light','rust','light','light','light','light','light','light','dark','light','rust','light','light','night'];
const presenters=[
 {name:'Andrey',title:'Contexto e requisitos',start:0,end:3},
 {name:'Gabriel',title:'Planejamento e desenho',start:3,end:6},
 {name:'Rayane',title:'Do acordo à entrega',start:6,end:10},
 {name:'Pedro',title:'Indicadores, IA e proteção',start:10,end:13},
 {name:'João Vitor',title:'Continuidade e melhoria',start:13,end:16}
];
const presenterIndex=presenters.map((person,p)=>`<section class="index-person" aria-labelledby="index-speaker-${p} index-person-${p}"><p class="index-person-label" id="index-speaker-${p}">${esc(person.name)} <span>Capítulos ${String(person.start+1).padStart(2,'0')}–${String(person.end).padStart(2,'0')}</span></p><h3 id="index-person-${p}">${esc(person.title)}</h3><div class="index-grid">${chapters.slice(person.start,person.end).map((c,j)=>{const i=person.start+j;return `<button data-go="${i}" aria-current="${i===0}"><span>${String(i+1).padStart(2,'0')}</span>${esc(labels[i])}</button>`;}).join('')}</div></section>`).join('');
const sections=chapters.map((c,i)=>{
 let extra='',buttons='';
 if(i===0){buttons=`<button class="primary" data-desktop="terminal">Abrir terminal ${arrow}</button><button class="secondary" data-go="1">Seguir a história ↓</button>`;extra='<p class="terminal-cue">Digite <code>start vereda</code> no computador e pressione Enter.</p>';}
 if(i===1)extra=`<aside class="strategy-note" aria-labelledby="strategy-title"><h3 id="strategy-title">${esc(c.strategy.title)}</h3><p>${esc(c.strategy.text)}</p></aside><div class="proof-tags"><span>Uma pessoa</span><span>Uma P2S</span><span>Cinco modelos + encomendas</span></div>`;
 if(i===2)extra='<div class="proof-tags"><span>Forma e cor</span><span>Data necessária</span><span>Prévia antes de imprimir</span></div>';
 if(i===3)extra='<div class="story-path"><span>Fila</span><i>+</i><span>Produção</span><i>+</i><span>Frete cotado</span></div>';
 if(i===4)extra='<div class="story-path"><span>SLR</span><i>→</i><span>UC</span><i>→</i><span>SLA</span><i>→</i><span>Monitorar</span><i>→</i><span>SIP</span></div>';
 if(i===5){buttons=`<button class="primary" data-studio>Abrir o notebook ${arrow}</button>`;extra='<p class="chapter-note">Você pode girar, fatiar e preparar um estudo de forma.</p>';}
 if(i===6){buttons=`<button class="primary" data-studio>Conferir a prévia ${arrow}</button>`;extra='<div class="proof-tags"><span>Peça</span><span>Preço</span><span>Prazo</span><span>Aprovação</span></div>';}
 if(i===7){extra='<div class="print-stat"><output id="print-progress" aria-label="Formação da peça">0%</output><span>da forma revelada pela rolagem</span></div><p class="chapter-note">Visualização artística. O tempo real é calculado no Bambu Studio para cada peça.</p>';}
 if(i===8)extra='<div class="proof-tags"><span>Forma</span><span>Cor</span><span>Tamanho</span><span>Nome</span></div>';
 if(i===9)extra='<div class="story-path"><span>Postagem</span><i>→</i><span>Rastreio</span><i>→</i><span>Entrega</span></div>';
 if(i===10){buttons=`<button class="primary" data-details="10">Examinar as seis metas ${arrow}</button>`;}
 if(i===11)extra='<div class="proof-tags"><span>Só encomendas</span><span>Sem dados pessoais</span><span>Revisão humana</span></div>';
 if(i===12)extra='<div class="story-path"><span>Modelar</span><i>→</i><span>Fatiar</span><i>→</i><span>Revisar</span><i>→</i><span>Aprovar</span></div>';
 if(i===13)extra='<div class="proof-tags"><span>Blender</span><span>Catálogo</span><span>Operação independente</span></div>';
 if(i===14)extra='<div class="story-path"><span>Medir</span><i>→</i><span>Revisar</span><i>→</i><span>Melhorar</span></div>';
 if(i===15){buttons=`<button class="primary" id="replay">Recomeçar a história ${arrow}</button><button class="secondary" data-details="15">Ver o fechamento</button>`;extra='<p class="hero-foot">Vereda · Palmas, Tocantins<br>Gerenciamento de serviços de TI · SLM e IA</p>';}
 const tag=i===0?'h1':'h2';return `<section class="chapter" id="${c.id}" data-stage="${c.stage}" data-tone="${tones[i]}" data-short="${esc(labels[i])}" data-layout="${[3,10,14].includes(i)?'reverse':'normal'}" aria-labelledby="title-${i}"><div class="chapter-copy"><p class="chapter-label">${labels[i]} <span>${String(i+1).padStart(2,'0')} / 16</span></p><${tag} id="title-${i}">${titles[i]}</${tag}><p class="story-body">${esc(c.body)}</p>${buttons?'<div class="chapter-actions">'+buttons+'</div>':''}${extra}${i!==10?`<button class="details-trigger" data-details="${i}">Conteúdo de SLM <span aria-hidden="true">↗</span></button>`:''}</div></section>`;
}).join('\n');
const out=`<!doctype html>
<html lang="pt-BR" class="no-js"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f1f0ec"><meta name="description" content="Da ideia à luz: uma experiência interativa sobre o serviço da Vereda. Explore um notebook, prepare uma peça e acompanhe a formação em camadas."><title>vereda — da ideia à luz</title><script>document.documentElement.classList.remove("no-js");document.documentElement.classList.add("page-loading");window.__veredaPageLoadFallback=setTimeout(function(){window.dispatchEvent(new Event("vereda:preload-timeout"));var loader=document.getElementById("page-loader");if(loader)loader.remove();document.documentElement.classList.remove("page-loading");},9000);document.documentElement.dataset.entry=location.hash&&location.hash.toLowerCase()!=="#hero"?"story":"closed";</script><style>#page-loader{position:fixed;inset:0;width:100%;height:100dvh;max-width:none;max-height:none;margin:0;padding:0;border:0;background:#f1f0ec;z-index:2147483000}.no-js #page-loader{display:none!important}html.page-loading{overflow:hidden}html.page-loading body>:not(#page-loader){visibility:hidden}</style><link rel="preload" href="assets/brand/manrope-latin-vf.woff2" as="font" type="font/woff2" crossorigin><link rel="icon" href="assets/brand/simbolo-app.png" type="image/png"><link rel="stylesheet" href="atelier.css?v=estrategia-servico"><link rel="stylesheet" href="studio.css"><link rel="stylesheet" href="notebook-desktop.css"><link rel="stylesheet" href="notebook-web.css"><link rel="stylesheet" href="notebook-words.css"><link rel="stylesheet" href="notebook-entry.css"><link rel="stylesheet" href="atelier-audio.css"><link rel="stylesheet" href="page-loader.css"></head>
<body data-tone="light">${pageLoader}<script src="page-loader.js"></script><a class="skip" href="#story">Ir para a história</a><header class="site-head"><a class="brand" href="#hero" aria-label="Vereda, início"><img src="assets/brand/logo-negativo.png" alt="vereda"></a><span class="head-note">Da ideia à luz · uma história sobre serviço</span><nav class="head-actions" aria-label="Controles da apresentação"><button class="text-button" id="motion" aria-pressed="false">Pausar movimento</button><button class="text-button" id="fullscreen">Tela cheia ↗</button><button class="text-button" data-index><span class="menu-icon" aria-hidden="true"><i></i><i></i><i></i></span> Índice</button></nav></header>
<div class="stage" aria-hidden="true"><canvas id="atelier-canvas"></canvas><div class="fallback-lamp"></div></div><div class="scene-controls" role="group" aria-label="Explorar a luminária"><button data-turn="-.45" aria-label="Girar luminária para a esquerda">↶</button><button data-turn=".45" aria-label="Girar luminária para a direita">↷</button><button data-light aria-label="Alternar luz da luminária" aria-pressed="true">☼</button></div><button class="mobile-studio-launch" data-studio>Entrar no computador ↗</button><span class="scene-hint">Experimente a peça</span><aside class="stage-caption"><strong id="scene-title">Um estudo de forma</strong><span id="scene-subtitle">Representação artística interativa</span></aside>
<noscript><p class="no-js-note">A história continua disponível abaixo. Para ler todas as respostas, abra a <a href="docs/folha-slm-respondida.html">folha de SLM respondida</a>. As experiências 3D precisam de JavaScript.</p></noscript>
<main id="story" tabindex="-1">${sections}</main>
<footer class="site-foot"><div class="footer-inner"><button class="index-button" data-index><span class="menu-icon" aria-hidden="true"><i></i><i></i><i></i></span><span id="active-name">Da ideia à luz</span></button><nav class="timeline-dots" aria-label="Capítulos">${chapters.map((c,i)=>`<button data-go="${i}" aria-label="${i+1}. ${esc(labels[i])}" aria-current="${i===0}"></button>`).join('')}</nav><a class="footer-source" href="docs/folha-slm-respondida.html" target="_blank" rel="noopener">A folha respondida ↗</a><span class="footer-count"><strong id="current-count">01</strong> / 16</span><div class="page-arrows"><button id="previous" aria-label="Capítulo anterior" disabled>←</button><button id="next" aria-label="Próximo capítulo">→</button></div></div></footer>
<dialog id="index-dialog" aria-labelledby="index-title"><div class="dialog-head"><h2 id="index-title">Uma história, cinco pessoas.</h2><button class="close-dialog" data-close aria-label="Fechar índice">×</button></div><div class="dialog-content"><p class="dialog-intro">Cada pessoa apresenta um trecho da história, na ordem abaixo. Escolha um capítulo para começar. Use as setas para apresentar; I abre o índice e N abre o conteúdo.</p><nav class="index-groups" aria-label="Índice dividido entre cinco pessoas">${presenterIndex}</nav></div></dialog>
<dialog id="content-dialog" aria-labelledby="content-title"><div class="dialog-head"><h2 id="content-title">O conteúdo por trás da cena</h2><button class="close-dialog" data-close aria-label="Fechar conteúdo">×</button></div><div class="dialog-content" id="content-body"></div></dialog><div class="toast" id="toast" role="status" hidden></div>
<script src="assets/vendor/three.min.js"></script><script src="assets/vendor/GLTFLoader.js"></script><script src="story-content.js?v=estrategia-servico"></script><script src="atelier-forms.js"></script><script src="notebook-stickers.js"></script><script src="notebook-input.js"></script><script src="notebook-entry.js"></script><script src="atelier-scene.js"></script><script src="studio.js"></script><script src="light-room.js"></script><script src="notebook-web.js"></script><script src="notebook-word-list.js"></script><script src="notebook-words.js"></script><script src="notebook-desktop.js"></script><script src="atelier.js"></script><script src="atelier-audio.js"></script></body></html>`;
fs.writeFileSync(path.join(base,'index.html'),out);console.log('Built',chapters.length,'chapters;',out.length,'bytes');
